[tools]
# DevOps tools (merged with base.mise.toml via /etc/mise/conf.d/)
terraform      = "latest"
awscli         = "latest"
opentofu       = "latest"
terragrunt     = "latest"
terraform-docs = "latest"
kubectl        = "latest"
helm           = "latest"
helmfile       = "latest"
k9s            = "latest"
kubeconform    = "latest"
argo-rollouts  = "latest"
kubelogin      = "latest"
argo           = "latest"
linkerd        = "latest"
gator          = "latest"
